from .autenticacion import *
from .actualizar_datos_usuario import *
from .recuperar_credenciales import *
from .funciones_inicio_sesion import *
from .pre_registro_personal import *
from .completar_registro import *
from .inscripcion_estudiante import *
from .pnf import *
from .seccion import *
from .materia import *
from .calendario_notas import *
from .actualizar_datos_usuario import *
from .asignacion_materia import *
from .aula import *
from .foro import *
from .panel_usuario import *
from .autoridades import *
from .planes_actividades import *
from .horario_academico import *