# Generated by Django 6.0.3 on 2026-08-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('predeterminada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Autoridades',
            fields=[
                ('id_autoridad', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CorteAcademico',
            fields=[
                ('id_corte_academico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_materia', models.CharField(max_length=100)),
                ('trayecto', models.CharField(max_length=10)),
                ('recuperacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleos',
            fields=[
                ('id_nucleo', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoCargarNotas',
            fields=[
                ('id_periodo_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEspecial',
            fields=[
                ('id_plan_especial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pnf',
            fields=[
                ('id_pnf', models.AutoField(primary_key=True, serialize=False)),
                ('pnf', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=60)),
                ('periodo_academico', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_identidad', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionCodigo',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_identidad', models.CharField(max_length=12)),
                ('token', models.CharField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10)),
                ('creado', models.DateTimeField()),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id_calendario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusEstudiante',
            fields=[
                ('id_estatus_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('ingreso', models.CharField(max_length=50)),
                ('descripcion_ingreso', models.CharField(max_length=30)),
                ('trayecto', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosEstudiante',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_estudiante/')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_carnet_discapacidad', models.CharField(max_length=50)),
                ('nro_registro_medico', models.CharField(max_length=5)),
                ('tipo_discapacidad', models.CharField(max_length=20)),
                ('grado_discapacidad', models.CharField(max_length=50)),
                ('causa_discapacidad', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoAuxiliar',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=25)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteCorte',
            fields=[
                ('id_estudiante_corte', models.AutoField(primary_key=True, serialize=False)),
                ('corte_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.corteacademico')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.grupoactividad'),
        ),
        migrations.CreateModel(
            name='InformacionSecundaria',
            fields=[
                ('id_secundaria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_institucion', models.CharField(max_length=100)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('fecha_grado', models.DateField()),
                ('codigo_sni_opsu', models.CharField(max_length=100, unique=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaAsignada',
            fields=[
                ('id_materia_asignada', models.AutoField(primary_key=True, serialize=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.materia')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.AddField(
            model_name='docente',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.CreateModel(
            name='AulaAcademica',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(max_length=100)),
                ('nombre_edificio', models.CharField(max_length=100)),
                ('piso_edificio', models.CharField(max_length=100)),
                ('id_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioCargarNotas',
            fields=[
                ('id_fecha_carga_nota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodocargarnotas')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoNotasMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.periodocargarnotas')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='id_pnf',
            field=models.ForeignKey(db_column='id_pnf', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.CreateModel(
            name='HorarioAcademica',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('turno_academico', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.aulaacademica')),
                ('id_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.periodocargarnotas')),
                ('id_pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.AddField(
            model_name='docente',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.CreateModel(
            name='PNFNucleo',
            fields=[
                ('id_pnf_nucleo', models.AutoField(primary_key=True, serialize=False)),
                ('id_nucleo', models.ForeignKey(db_column='id_nucleo', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_pnf', models.ForeignKey(db_column='id_pnf', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionAcademica',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.aulaacademica')),
                ('id_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionEstudiante',
            fields=[
                ('id_seccion_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.estudiante')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.seccionacademica')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id_residencia', models.AutoField(primary_key=True, serialize=False)),
                ('condicion_residencia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_residencia', models.CharField(max_length=100)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencia', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nacimiento',
            fields=[
                ('id_nacimiento', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nacimiento', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario'),
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPreofesion',
            fields=[
                ('id_dato_academico', models.AutoField(primary_key=True, serialize=False)),
                ('profesion_pregrado', models.CharField(max_length=150)),
                ('universidad_egreso_pregrado', models.CharField(max_length=150)),
                ('pais_profesion_pregrado', models.CharField(max_length=150)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_profesional', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=160, unique=True)),
                ('clave', models.CharField(max_length=160)),
                ('tipo_cuenta', models.CharField(choices=[('ADMIN', 'Administrativo'), ('EST', 'Estudiante')], max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorPNF',
            fields=[
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ControlEstudio',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_suplete', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_personal', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('correo_alternativo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_estudiante_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='docente',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_docente_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='directorgeneral',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo'), name='uq_director_usuario'),
        ),
        migrations.AddConstraint(
            model_name='coordinadorpnf',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_coordinadorpnf_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='controlestudio',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo'), name='uq_control_usuario_nucleo'),
        ),
    ]
