# Generated by Django 6.0.3 on 2026-07-30 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridades',
            fields=[
                ('id_autoridad', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CorteAcademico',
            fields=[
                ('id_corte_academico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_materia', models.CharField(max_length=100)),
                ('trayecto', models.CharField(max_length=10)),
                ('recuperacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('nombre_tabla', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleos',
            fields=[
                ('id_nucleo', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_pefil', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_periodo_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEspecial',
            fields=[
                ('id_plan_especial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pnf',
            fields=[
                ('id_pnf', models.AutoField(primary_key=True, serialize=False)),
                ('pnf', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=40)),
                ('periodo_academico', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('cedula_identidad', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionCodigo',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_identidad', models.CharField(max_length=12)),
                ('token', models.CharField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10)),
                ('creado', models.DateTimeField()),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('EmailField', 'EmailField'), ('TextField', 'TextField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField')], max_length=30)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('null', models.BooleanField(default=False)),
                ('blank', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('relacion', models.CharField(blank=True, max_length=100)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='inicio_sesion.modelodinamico')),
            ],
        ),
        migrations.CreateModel(
            name='AulaAcademica',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(max_length=100)),
                ('nombre_edificio', models.CharField(max_length=100)),
                ('piso_edificio', models.CharField(max_length=100)),
                ('id_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id_fecha_academica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.periodoacademico')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='id_pnf',
            field=models.ForeignKey(db_column='id_pnf', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.CreateModel(
            name='HorarioAcademica',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('turno_academico', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.aulaacademica')),
                ('id_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.periodoacademico')),
                ('id_pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='PNFNucleo',
            fields=[
                ('id_pnf_nucleo', models.AutoField(primary_key=True, serialize=False)),
                ('id_nucleo', models.ForeignKey(db_column='id_nucleo', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_pnf', models.ForeignKey(db_column='id_pnf', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionAcademica',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.aulaacademica')),
                ('id_nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('id_pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id_residencia', models.AutoField(primary_key=True, serialize=False)),
                ('condicion_residencia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_residencia', models.CharField(max_length=100)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencia', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nacimiento',
            fields=[
                ('id_nacimiento', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nacimiento', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=160, unique=True)),
                ('clave', models.CharField(max_length=160)),
                ('tipo_cuenta', models.CharField(choices=[('ADMIN', 'Administrativo'), ('EST', 'Estudiante')], max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_suplete', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_personal', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('correo_alternativo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.calendarioacademico')),
                ('periodo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.periodomateria')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('calendario', 'periodo_materia'), name='uq_calendario_periodo_materia')],
            },
        ),
    ]
