# Generated by Django 6.0.3 on 2026-06-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacioncodigo',
            name='intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
