# Generated by Django 6.0.3 on 2026-07-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='recuperacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='tipo_materia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='trayecto',
            field=models.CharField(max_length=100),
        ),
    ]
