# Generated by Django 6.0.3 on 2026-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleos',
            name='id_nucleo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='id_pefil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pnf',
            name='id_pnf',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
