# Generated by Django 6.0.3 on 2026-06-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEstudiante',
            fields=[
                ('id_oficio', models.AutoField(primary_key=True, serialize=False)),
                ('oficio_practica', models.CharField(max_length=100)),
                ('deporte_practica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PadresEstudiante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padresEstudiante', to='inicio_sesion.usuario')),
            ],
        ),
    ]
