# Generated by Django 6.0.3 on 2026-08-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='tipo_materia',
        ),
    ]
