# Generated by Django 6.0.3 on 2026-06-11 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_oficioestudiante_padresestudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OficioEstudiante',
        ),
    ]
