# Generated by Django 6.0.3 on 2026-08-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materiaasignada',
            name='uq_materia_seccion',
        ),
        migrations.AddConstraint(
            model_name='docenteasignadomateria',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'SECUNDARIO')), fields=('materia_asignada',), name='uq_docente_secundario'),
        ),
        migrations.AddConstraint(
            model_name='materiaasignada',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('materia', 'seccion'), name='uq_materia_seccion_activa'),
        ),
    ]
