# Generated by Django 6.0.3 on 2026-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_alter_contacto_id_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo_alternativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
