# Generated by Django 6.0.3 on 2026-08-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentohorario',
            name='archivo',
            field=models.CharField(max_length=500),
        ),
    ]
