# Generated by Django 6.0.3 on 2026-08-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
