# Generated by Django 6.0.3 on 2026-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='htea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='htei',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
