# Generated by Django 6.0.3 on 2026-07-31 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEstudio',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinadorPNF',
            fields=[
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Perfiles',
        ),
        migrations.RemoveField(
            model_name='modelodinamico',
            name='nombre_tabla',
        ),
        migrations.AddField(
            model_name='campomodelo',
            name='primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campomodelo',
            name='upload_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campomodelo',
            name='relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='campomodelo',
            name='tipo',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('DecimalField', 'DecimalField'), ('FloatField', 'FloatField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('BooleanField', 'BooleanField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField'), ('FileField', 'FileField')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='controlestudio',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo'), name='uq_control_usuario_nucleo'),
        ),
        migrations.AddConstraint(
            model_name='coordinadorpnf',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_coordinadorpnf_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='directorgeneral',
            constraint=models.UniqueConstraint(fields=('usuario',), name='uq_director_usuario'),
        ),
        migrations.AddConstraint(
            model_name='docente',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_docente_usuario_nucleo_pnf'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo', 'pnf'), name='uq_estudiante_usuario_nucleo_pnf'),
        ),
    ]
