# Generated by Django 6.0.3 on 2026-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_alter_nucleos_id_nucleo_alter_perfiles_id_pefil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnfnucleo',
            name='id_pnf_nucleo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
