# Generated by Django 6.0.3 on 2026-07-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomodelo',
            name='tipo',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField'), ('EmailField', 'EmailField'), ('TextField', 'TextField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField')], max_length=30),
        ),
    ]
