# Generated by Django 6.0.3 on 2026-07-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_alter_materia_codigo_alter_materia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioacademico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
