# Generated by Django 6.0.3 on 2026-08-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_alter_documentohorario_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoauxiliar',
            name='cedula_identidad',
            field=models.CharField(max_length=15),
        ),
    ]
