# Generated by Django 6.0.3 on 2026-07-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_calendarioacademico_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendariomateria',
            name='id_calendario_materia',
        ),
        migrations.AddField(
            model_name='calendariomateria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendariomateria',
            name='calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.calendarioacademico'),
        ),
        migrations.AlterField(
            model_name='calendariomateria',
            name='periodo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.periodomateria'),
        ),
        migrations.AddConstraint(
            model_name='calendariomateria',
            constraint=models.UniqueConstraint(fields=('calendario', 'periodo_materia'), name='uq_calendario_periodo_materia'),
        ),
    ]
