# Generated by Django 6.0.3 on 2026-07-30 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inicio_sesion', '0003_alter_campomodelo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campomodelo',
            name='primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campomodelo',
            name='relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
