# Generated by Django 6.0.3 on 2026-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_alter_pnfnucleo_id_pnf_nucleo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilespnf',
            name='id_perfil_pnf',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarionucleo',
            name='id_usuario_nucleo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='id_perfil_asignado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
