# Generated by Django 6.0.3 on 2026-08-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_alter_usuario_estado_civil_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinadorpnf',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.AlterField(
            model_name='coordinadorpnf',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.pnf'),
        ),
    ]
