# Generated by Django 6.0.3 on 2026-08-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_remove_materia_tipo_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionacademica',
            name='fecha_creacion',
        ),
    ]
