# Generated by Django 6.0.3 on 2026-08-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_alter_materia_htea_alter_materia_htei'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaasignada',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.seccionacademica'),
        ),
    ]
