# Generated by Django 6.0.3 on 2026-08-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_materia_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlestudio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coordinadorpnf',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
