# Generated by Django 6.0.3 on 2026-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_delete_oficioestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacioncodigo',
            name='token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
