# Generated by Django 6.0.3 on 2026-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_verificacioncodigo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacimiento',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
