# Generated by Django 6.0.3 on 2026-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_materiaasignada_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaasignada',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='materiaasignada',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='materiaasignada',
            name='fecha_suspension',
        ),
        migrations.AddField(
            model_name='docenteasignadomateria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='docenteasignadomateria',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='docenteasignadomateria',
            name='fecha_suspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
