# Generated by Django 6.0.3 on 2026-07-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_campomodelo_primary_key_alter_campomodelo_relacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelodinamico',
            name='nombre_tabla',
        ),
    ]
