# Generated by Django 6.0.3 on 2026-08-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_alter_coordinadorpnf_nucleo_alter_coordinadorpnf_pnf_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directorgeneral',
            name='uq_director_usuario',
        ),
        migrations.AddField(
            model_name='directorgeneral',
            name='nucleo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos'),
        ),
        migrations.AddConstraint(
            model_name='directorgeneral',
            constraint=models.UniqueConstraint(fields=('usuario', 'nucleo'), name='uq_director_usuario'),
        ),
    ]
