# Generated by Django 6.0.3 on 2026-07-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_remove_calendariomateria_id_calendario_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridades',
            fields=[
                ('id_autoridad', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100, unique=True)),
                ('id_nucleo', models.ForeignKey(db_column='id_nucleo', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.nucleos')),
            ],
        ),
    ]
