# Generated by Django 6.0.3 on 2026-07-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_autoridades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoridades',
            name='id_nucleo',
        ),
    ]
