# Generated by Django 6.0.3 on 2026-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_remove_modelodinamico_nombre_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomodelo',
            name='tipo',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('DecimalField', 'DecimalField'), ('FloatField', 'FloatField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('BooleanField', 'BooleanField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField')], max_length=30),
        ),
    ]
