# Generated by Django 6.0.3 on 2026-06-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0005_nacimiento_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiante/'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='nombre_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
