# Generated by Django 6.0.3 on 2026-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0006_documentosestudiante_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padresestudiante',
            name='parentesco',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
