# Generated by Django 6.0.3 on 2026-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0006_alter_campomodelo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campomodelo',
            name='upload_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campomodelo',
            name='tipo',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('EmailField', 'EmailField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('DecimalField', 'DecimalField'), ('FloatField', 'FloatField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('BooleanField', 'BooleanField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField'), ('FileField', 'FileField')], max_length=30),
        ),
    ]
