# Generated by Django 6.0.3 on 2026-06-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0007_padresestudiante_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padresestudiante',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padresEstudiante', to='inicio_sesion.usuario'),
        ),
    ]
