# Generated by Django 6.0.3 on 2026-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0008_alter_padresestudiante_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacimiento',
            name='id_nacimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='id_residencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
