# Generated by Django 6.0.3 on 2026-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0009_alter_nacimiento_id_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionsecundaria',
            name='codigo_sni_opsu',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='informacionsecundaria',
            name='nombre_institucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='informacionsecundaria',
            name='tipo_institucion',
            field=models.CharField(max_length=100),
        ),
    ]
