# Generated by Django 6.0.3 on 2026-06-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0010_alter_informacionsecundaria_codigo_sni_opsu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospreofesion',
            name='pais_profesion_pregrado',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datospreofesion',
            name='profesion_pregrado',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datospreofesion',
            name='universidad_egreso_pregrado',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gacetaoficial',
            name='gaceta_oficial',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='direccion_nacimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='parroquia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='condicion_residencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='direccion_residencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='parroquia',
            field=models.CharField(max_length=100),
        ),
    ]
