# Generated by Django 6.0.3 on 2026-08-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio_sesion', '0003_alter_documentohorario_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanActividades',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_unidad', models.CharField(max_length=255)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contenido_unidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('promedio_tramo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=100)),
                ('trayecto', models.CharField(max_length=20)),
                ('fecha_promedio', models.DateField()),
                ('docente_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='inicio_sesion.docenteasignadomateria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='inicio_sesion.estudiante')),
                ('periodo_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='inicio_sesion.periodonotasmateria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCalificacionesUnidad',
            fields=[
                ('id_detalle_calificaciones_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nota_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_unidad', to='notas_academicas.calificaciones')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_unidad', to='notas_academicas.detalleplanactividades')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanEvaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_evaluacion', models.CharField(max_length=100)),
                ('fecha_evaluacion', models.DateField()),
                ('detalle_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='notas_academicas.detalleplanactividades')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCalificaciones',
            fields=[
                ('id_detalle_calificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_evaluacion', to='notas_academicas.calificaciones')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='notas_academicas.detalleplanevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActividadAcademica',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado_aceptacion', models.CharField(choices=[('ESPERA', 'En espera'), ('ACEPTADA', 'Aceptada'), ('DENEGADA', 'Denegada')], default='ESPERA', max_length=10)),
                ('materia_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.materiaasignada')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.nucleos')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodocargarnotas')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.pnf')),
            ],
        ),
        migrations.AddField(
            model_name='detalleplanactividades',
            name='plan_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.planactividadacademica'),
        ),
        migrations.CreateModel(
            name='PromedioFinal',
            fields=[
                ('id_promedio_final', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=20)),
                ('promedio_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_promedio', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='inicio_sesion.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promedios_finales', to='inicio_sesion.materia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='calificaciones',
            constraint=models.UniqueConstraint(fields=('periodo_materia', 'docente_asignado', 'estudiante'), name='uq_calificacion_estudiante_periodo_docente'),
        ),
    ]
