# Generated by Django 6.0.3 on 2026-08-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planactividadacademica',
            name='estado_aceptacion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Coordinador'), ('ACEPTADA', 'Aceptada'), ('DENEGADA', 'Denegada')], default='ESPERA', max_length=10),
        ),
    ]
