# Generated by Django 6.0.3 on 2026-08-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0002_alter_planactividadacademica_estado_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planactividadacademica',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planactividadacademica',
            name='estado_aceptacion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Coordinador'), ('ACEPTADA', 'Aceptada'), ('DENEGADA', 'Denegada')], default='BORRADOR', max_length=10),
        ),
    ]
