# Generated by Django 6.0.3 on 2026-08-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_alter_contactoauxiliar_cedula_identidad'),
        ('notas_academicas', '0003_planactividadacademica_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='docente_asignado',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='materia_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='inicio_sesion.materiaasignada'),
        ),
    ]
