# Generated by Django 6.0.3 on 2026-08-16 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0004_remove_calificaciones_docente_asignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecalificaciones',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='detallecalificaciones',
            name='evaluacion',
        ),
        migrations.RenameField(
            model_name='calificaciones',
            old_name='estado',
            new_name='condicion',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='asistencia',
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ]
            ),
        ),
        migrations.DeleteModel(
            name='DetalleCalificaciones',
        ),
    ]