# Generated by Django 6.0.3 on 2026-08-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_alter_contactoauxiliar_cedula_identidad'),
        ('notas_academicas', '0005_remove_detallecalificaciones_calificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDetalleNota',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.PositiveSmallIntegerField()),
                ('nota_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_nueva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asistencia_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asistencia_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialModificacionNotas',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('trayecto', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historialdetallenota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.estudiante'),
        ),
        migrations.AddField(
            model_name='historialmodificacionnotas',
            name='docente_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.docenteasignadomateria'),
        ),
        migrations.AddField(
            model_name='historialmodificacionnotas',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.periodocargarnotas'),
        ),
        migrations.AddField(
            model_name='historialmodificacionnotas',
            name='usuario_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio_sesion.usuario'),
        ),
        migrations.AddField(
            model_name='historialdetallenota',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notas_academicas.historialmodificacionnotas'),
        ),
    ]
