# Generated by Django 6.0.3 on 2026-08-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_alter_contactoauxiliar_cedula_identidad'),
        ('notas_academicas', '0006_historialdetallenota_historialmodificacionnotas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTrayectoEstudiante',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('trayecto_anterior', models.CharField(max_length=20)),
                ('trayecto_nuevo', models.CharField(max_length=20)),
                ('cantidad_materias', models.PositiveSmallIntegerField()),
                ('materias_reprobadas', models.PositiveSmallIntegerField()),
                ('materias_mala_asistencia', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('puede_pasar', models.BooleanField(default=False)),
                ('motivo', models.TextField()),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='calificaciones',
            name='uq_calificacion_estudiante_periodo_docente',
        ),
        migrations.AddField(
            model_name='historialtrayectoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_trayecto', to='inicio_sesion.estudiante'),
        ),
    ]
