# Generated by Django 6.0.3 on 2026-08-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_alter_contactoauxiliar_cedula_identidad'),
        ('notas_academicas', '0007_historialtrayectoestudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_reparacion', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inicio_sesion.estudiante')),
                ('id_materia_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inicio_sesion.materiaasignada')),
            ],
        ),
    ]
