# Generated by Django 6.0.3 on 2026-08-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_academicas', '0008_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='trayecto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
